import Link from "next/link";
import type { Observation, SoilTerritoryProfile, TerritoryDomainProfile, TerritoryProfile, WaterProfile } from "../lib/data";

const labels: Record<string, string> = {
  soil_net_consumption_hectares: "Incremento netto di suolo consumato", soil_gross_consumption_hectares: "Incremento lordo di suolo consumato", soil_restoration_hectares: "Ripristino di suolo", soil_consumed_hectares: "Suolo consumato", soil_consumed_share: "Quota di suolo consumato",
  water_total_precipitation_mm: "Precipitazione totale", water_total_precipitation_mm_zonal_mean: "Precipitazione totale", water_actual_evapotranspiration_mm: "Evapotraspirazione effettiva", water_actual_evapotranspiration_mm_zonal_mean: "Evapotraspirazione effettiva", water_internal_flow_mm: "Risorsa idrica rinnovabile", water_internal_flow_mm_zonal_mean: "Risorsa idrica rinnovabile", water_aquifer_recharge_mm: "Ricarica acquiferi", water_aquifer_recharge_mm_zonal_mean: "Ricarica acquiferi", water_surface_runoff_mm: "Ruscellamento superficiale", water_surface_runoff_mm_zonal_mean: "Ruscellamento superficiale",
};
const levelLabels: Record<string, string> = { municipality: "Comune", province: "Provincia", region: "Regione", country: "Italia" };
type Analytics = { changes?: Record<string, { value?: number | null; status?: string | null }>; trend?: { status?: string | null; direction?: string | null }; benchmarks?: Record<string, { percentileStatus?: string | null; rankStatus?: string | null }> };

function value(observation: Observation | { value: number; unit: string }) { return `${observation.value.toLocaleString("it-IT", { maximumFractionDigits: 1 })} ${observation.unit}`; }
function period(start: string, end: string) { return start.slice(0, 4) === end.slice(0, 4) ? start.slice(0, 4) : `${start.slice(0, 4)}–${end.slice(0, 4)}`; }
function kind(domain: TerritoryDomainProfile) { return domain.dataKind === "official_model" ? "Stima modellistica ufficiale" : domain.dataKind === "derived_metric" ? "Elaborazione derivata" : domain.dataKind === "mixed" ? "Fonti e metodi distinti" : "Osservazione ufficiale"; }
function temporal(domain: TerritoryDomainProfile) { return ({ annual_series: "Serie annuale", interval_series: "Serie per intervalli pubblicati", sparse_series: "Annualità pubblicate non continue", snapshot: "Snapshot", change_period: "Periodo di cambiamento", mixed: "Prodotti distinti" } as const)[domain.temporal]; }
function unavailable(domain: TerritoryDomainProfile) { return domain.reason === "not_in_published_coverage" ? "Territorio fuori dalla copertura pubblicata" : "Fonte non pubblicata a questo livello"; }

function SoilDetail({ profile }: { profile: SoilTerritoryProfile }) {
  const net = profile.latestObservations.find((item) => item.metricId === "soil_net_consumption_hectares");
  const history = profile.historicalSeries.find((item) => item.metricId === "soil_net_consumption_hectares");
  const analytics = profile.derivedMetrics.find((item) => item.metricId === "soil_net_consumption_hectares") as Analytics | undefined;
  return <div className="territory-domain-detail-grid"><section><p className="eyebrow">Indicatore principale</p><h3>Incremento netto</h3>{net ? <><strong>{value(net)}</strong><p>{period(net.periodStart, net.periodEnd)} · osservazione ufficiale.</p></> : <p>Non pubblicato per questo territorio.</p>}</section><section><p className="eyebrow">Analytics pubblicate</p><h3>Confronti ammessi</h3><dl>{[["previous", "Periodo precedente"], ["fiveYears", "Cinque anni"], ["tenYears", "Dieci anni"]].map(([id, label]) => <div key={id}><dt>{label}</dt><dd>{analytics?.changes?.[id]?.status === "available" ? `${analytics.changes[id].value?.toLocaleString("it-IT", { maximumFractionDigits: 1 })} ha` : "Non disponibile"}</dd></div>)}<div><dt>Trend</dt><dd>{analytics?.trend?.status === "available" ? analytics.trend.direction : "Non stimabile"}</dd></div></dl></section><section className="territory-domain-series"><p className="eyebrow">Serie ufficiale</p><h3>Storico pubblicato</h3>{history ? <div className="table-scroll"><table><caption>Incremento netto di suolo consumato</caption><thead><tr><th>Periodo</th><th>Valore</th></tr></thead><tbody>{history.values.map(([id, start, end, amount, unit]) => <tr key={id}><th scope="row">{period(start, end)}</th><td>{amount.toLocaleString("it-IT", { maximumFractionDigits: 1 })} {unit}</td></tr>)}</tbody></table></div> : <p>Nessuna serie pubblicata.</p>}</section></div>;
}

function WaterDetail({ profile, province }: { profile: WaterProfile; province: boolean }) {
  return <div className="territory-water-detail"><p>{province ? "Elaborazione Stato d’Italia su raster ISPRA BIGBANG 10.0 · media zonale pesata per area. Non è un dato provinciale ufficiale ISPRA." : "Stime modellistiche annuali ufficiali ISPRA BIGBANG 10.0."}</p>{province && <p className="territory-detail-note">Nessun delta, trend, interpolazione o crosswalk è calcolato fra geometry reference differenti.</p>}<div className="table-scroll"><table><caption>Metriche idriche disponibili</caption><thead><tr><th>Indicatore</th><th>Periodo</th><th>Valore</th></tr></thead><tbody>{profile.latestObservations.map((item) => <tr key={item.metricId}><th scope="row">{labels[item.metricId] ?? item.metricId}</th><td>{item.periodEnd.slice(0, 4)}</td><td>{value(item)}</td></tr>)}</tbody></table></div><details><summary>Annualità pubblicate e geometrie</summary>{profile.historicalSeries.map((series) => <section key={series.metricId}><h4>{labels[series.metricId] ?? series.metricId}</h4><div className="table-scroll"><table><thead><tr><th>Anno</th><th>Valore</th>{province && <th>Geometria</th>}</tr></thead><tbody>{series.values.map(([year, amount], index) => <tr key={year}><th scope="row">{year}</th><td>{amount.toLocaleString("it-IT", { maximumFractionDigits: 1 })} mm</td>{province && <td>{series.points?.[index]?.territoryGeometryReference ?? "Non dichiarata"}</td>}</tr>)}</tbody></table></div></section>)}</details></div>;
}

function DomainDetail({ domain, level }: { domain: TerritoryDomainProfile; level: string }) {
  if (domain.detail?.kind === "soil") return <SoilDetail profile={domain.detail.profile} />;
  if (domain.detail?.kind === "water") return <WaterDetail profile={domain.detail.profile} province={level === "province"} />;
  if (domain.id === "emissions") return <p>La disaggregazione ISPRA è per inquinante e attività SNAP: questo profilo non somma combinazioni, non crea un totale provinciale e non rappresenta qualità dell’aria.</p>;
  if (domain.id === "risk") return <p>Snapshot ISPRA IdroGEO: alluvioni 2020 e frane 2024 sono letture distinte. Non viene calcolato un trend tra indicatori o anni diversi.</p>;
  if (domain.id === "forests") return <p>INFC ufficiale e prodotti Copernicus derivati restano separati per fonte, metrica e geometria. Un confronto è ammesso solo dentro lo stesso prodotto compatibile.</p>;
  return <p>Consulta l’esploratore per il dettaglio pubblicato.</p>;
}

export function TerritoryProfile({ profile }: { profile: TerritoryProfile }) {
  const parents = profile.territory.parents.map((parent) => parent.name).join(" · ");
  const available = profile.domains.filter((domain) => domain.availability === "available");
  return <section className="territory-site-layout"><div className="territory-site-content"><header className="profile-head"><p className="eyebrow">{levelLabels[profile.territory.level]} · ISTAT {profile.territory.istatCode}</p><h1>{profile.territory.name}</h1>{parents && <p className="profile-parent">{parents}</p>}<p className="muted">Confini di riferimento: {profile.territory.referenceDate}</p></header><nav className="territory-profile-nav" aria-label="Sezioni del profilo"><a href="#domini">Quadro</a><a href="#dettagli">Dettagli</a>{available.map((domain) => <Link key={domain.id} href={domain.href}>Apri {domain.title}</Link>)}</nav><section id="domini" className="territory-domain-summary" tabIndex={-1} aria-labelledby="territory-domains-title"><header><div><p className="eyebrow">Quadro del territorio</p><h2 id="territory-domains-title">Copertura e natura dei dati</h2></div><p>I domini restano indipendenti: nessuna somma tra fonti, periodo inventato o valore assente trasformato in zero.</p></header><div className="territory-domain-list">{profile.domains.map((domain) => <article key={domain.id} className={`territory-domain-signal territory-domain-signal--${domain.id}${domain.availability === "unavailable" ? " is-unavailable" : ""}`}><header><span>{domain.title}</span><b>{temporal(domain)}</b></header>{domain.availability === "available" ? <><p className="territory-domain-kind">{kind(domain)}</p>{domain.latest ? <strong>{value(domain.latest)}</strong> : <h3>Disponibile nell’esploratore</h3>}<p>{domain.label ?? domain.source}</p><small>{domain.latest ? period(domain.latest.periodStart, domain.latest.periodEnd) : "Copertura pubblicata"} · {domain.source}</small><Link className="territory-domain-open" href={domain.href}>Apri {domain.title} <span aria-hidden="true">→</span></Link></> : <><h3>Non disponibile</h3><p>{unavailable(domain)}</p><small>{domain.source}</small></>}</article>)}</div></section><section id="dettagli" className="territory-domain-details" tabIndex={-1} aria-labelledby="territory-details-title"><header><p className="eyebrow">Dettagli</p><h2 id="territory-details-title">Letture per dominio</h2></header>{available.map((domain) => <details key={domain.id} className={`territory-domain-disclosure territory-domain-disclosure--${domain.id}`} open={domain.id === "soil" || domain.id === "water"}><summary><span>{domain.title}</span><small>{kind(domain)} · {temporal(domain)}</small></summary><div><DomainDetail domain={domain} level={profile.territory.level} /><Link href={domain.href}>Apri esploratore {domain.title} →</Link></div></details>)}</section></div></section>;
}
